version: 2
jobs:
  test:
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get -v -t -d ./...

      - run: go get github.com/jstemmer/go-junit-report
      - run: go test -v ./... | tee ${TEST_RESULTS}/go-test.out
      - run: go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml
      - store_test_results:
          path: /tmp/test-results

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

workflows:
  version: 2
  build:
    jobs:
      - test
