name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test_and_build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Cache modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get github.com/onsi/ginkgo/ginkgo

    - name: Test
      run: make test
      env:
        SECURE_API_TOKEN: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
        SECURE_URL: https://secure.sysdig.com

    - name: Build Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.SYSDIGLABS_DOCKERHUB_USER }}
        password: ${{ secrets.SYSDIGLABS_DOCKERHUB_TOKEN }}
        repository: sysdiglabs/harbor-scanner-sysdig-secure
        dockerfile: build/Dockerfile
        add_git_labels: true
        tags: ci
